### ISSUE TITLE
BILD Tracking

### ISSUE THREAD

**Issue by harry-stark** [LAION-AI/Big-Interleaved-Dataset#1]
This issue will track the overall progress of BILD.

Presently, BILD is divided into three phases. All of these are being tracked separately.

- [ ] Phase 1: Data extraction from [common crawl](https://commoncrawl.org/), maybe licensed part of the internet archive from [Webis group](https://webis.de/research/web-archive.html). 

- [ ] Phase 2: Data filtering for NSFW components, data quality, duplicated data, and other broad things.

- [ ] Phase 3: Filtered data can be used for creating dataset of various modalities. However, this project would like to tackle the interleaved format.
